DROP TABLE IF EXISTS SENSOR;
DROP TABLE IF EXISTS LIGHT;
DROP TABLE IF EXISTS FAN;
DROP TABLE IF EXISTS DOOR;


CREATE TABLE SENSOR (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TIME TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),
    HUMIDITY TEXT NOT NULL,
    TEMPERATURE TEXT NOT NULL
);

CREATE TABLE LIGHT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TIME TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),
    LIGHT TEXT NOT NULL
);

CREATE TABLE FAN (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TIME TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),
    FAN TEXT NOT NULL
);

CREATE TABLE DOOR (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TIME TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),
    DOOR TEXT NOT NULL
);
