DROP TABLE IF EXISTS DATABASE;

CREATE TABLE DATABASE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TIME TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),
    HUMIDITY TEXT NOT NULL,
    TEMPERATURE TEXT NOT NULL

);
